before_install:
  - printf "CPU:"
  - grep model\ name /proc/cpuinfo | head -1 | cut -f2 -d:
  - printf "CPU Cores:" && printf " " # workaround for https://github.com/travis-ci/travis-yaml/issues/81
  - grep -c processor /proc/cpuinfo
  - sudo add-apt-repository ppa:pypy/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq pypy
  - /usr/bin/env pypy --version
install: true
script:
  - make
  - make test
sudo: required
dist: trusty
notifications:
  email:
    - post@davidak.de
